# Generated by Django 4.2.6 on 2023-10-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poketasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='abilities',
        ),
        migrations.DeleteModel(
            name='Ability',
        ),
    ]
