# Generated by Django 4.2.6 on 2023-10-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poketasks', '0002_remove_pokemon_abilities_delete_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
